### ISSUE TITLE
No module named mockups, but already there! Debian

### ISSUE THREAD

**Issue by piotrekm** [sorl/django-mockups#1]
<pre>x@debian:~/project/alpha$ ./manage.py mockups
Traceback (most recent call last):
  File "./manage.py", line 14, in <module>
    execute_manager(settings)
  File "/home/g00fy/.python/lib/python2.6/site-packages/django/core/management/__init__.py", line 438, in execute_manager
    utility.execute()
  File "/home/g00fy/.python/lib/python2.6/site-packages/django/core/management/__init__.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/g00fy/.python/lib/python2.6/site-packages/django/core/management/__init__.py", line 261, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/g00fy/.python/lib/python2.6/site-packages/django/core/management/__init__.py", line 67, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/g00fy/.python/lib/python2.6/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/usr/local/lib/python2.6/dist-packages/mockups/management/commands/mockups.py", line 32, in <module>
    from ..mockups import create, signals, autodiscover
ImportError: No module named mockups</pre>

but it is installed:

<pre>x@debian:~/project/alpha$ python
Python 2.6.6 (r266:84292, Dec 26 2010, 22:31:48)
[GCC 4.4.5] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mockups
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.6/dist-packages/mockups/__init__.py", line 2, in <module>
    from mockups.factory import Factory
  File "/usr/local/lib/python2.6/dist-packages/mockups/factory.py", line 2, in <module>
    from django.db import models
  File "/home/g00fy/.python/lib/python2.6/site-packages/django/db/__init__.py", line 14, in <module>
    if not settings.DATABASES:
  File "/home/g00fy/.python/lib/python2.6/site-packages/django/utils/functional.py", line 276, in __getattr__
    self._setup()
  File "/home/g00fy/.python/lib/python2.6/site-packages/django/conf/__init__.py", line 40, in _setup
    raise ImportError("Settings cannot be imported, because environment variable %s is undefined." % ENVIRONMENT_VARIABLE)
ImportError: Settings cannot be imported, because environment variable DJANGO_SETTINGS_MODULE is undefined.
>>></pre>

**Comment by sorl** [comment]
The first problem is the relative imports, python changed the behaviour for different versions and even subversions, so i guess you are using a version that does not work, i have to look into this. If you want to try #2 do python manage.py shell. I am away for a week so I will not have time to look into this until im back.

**Comment by ouhouhsami** [comment]
It's working in my environment w/ :
from ...helpers import create, autodiscover
from ... import signals
instead of 
from ..mockups import create, signals, autodiscover

**Comment by kheast** [comment]
Same problem as OP on OS-X 10.67 / Python 2.6.6.  Workaround suggested by ouhouhsami works.
Thanks for a very helpful package and thanks for the assistance.

**Comment by sorl** [comment]
fixed

**Comment by mriveros** [comment]
How fixed this error??
