### ISSUE TITLE
limit_choices_to with Q object not supported

### ISSUE THREAD

**Issue by digitalfox** [sorl/django-mockups#2]
Hello,

Thanks for django-mockups, it is a nice tool. But I found the following bug. When "limit_choices' parameter is used with Q, mockups crash.

I have the following field in my models : 
    staffing = models.ManyToManyField(Consultant, blank=True, limit_choices_to=Q(active=True))

And mockups crash with the following stacktrace : 
./manage.py mockups leads.lead:20
/usr/lib64/python2.6/site-packages/django_mockups-0.4.6-py2.6.egg/mockups/helpers.py:21: UserWarning: Model `Lead` not in registry
  warnings.warn('Model `%s` not in registry' % model.**name**)
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_manager(settings)
  File "/usr/lib64/python2.6/site-packages/django/core/management/**init**.py", line 438, in execute_manager
    utility.execute()
  File "/usr/lib64/python2.6/site-packages/django/core/management/**init**.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib64/python2.6/site-packages/django/core/management/base.py", line 191, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/usr/lib64/python2.6/site-packages/django/core/management/base.py", line 220, in execute
    output = self.handle(_args, *_options)
  File "/usr/lib64/python2.6/site-packages/django/db/transaction.py", line 299, in _commit_on_success
    res = func(_args, *_kw)
  File "/usr/lib64/python2.6/site-packages/django_mockups-0.4.6-py2.6.egg/mockups/management/commands/mockups.py", line 217, in handle
    create(model, count, *_kwargs)
  File "/usr/lib64/python2.6/site-packages/django_mockups-0.4.6-py2.6.egg/mockups/helpers.py", line 107, in create
    return mockup.create(count)
  File "/usr/lib64/python2.6/site-packages/django_mockups-0.4.6-py2.6.egg/mockups/base.py", line 341, in create
    instance = self.create_one(commit=commit)
  File "/usr/lib64/python2.6/site-packages/django_mockups-0.4.6-py2.6.egg/mockups/base.py", line 321, in create_one
    self.process_m2m(instance, field)
  File "/usr/lib64/python2.6/site-packages/django_mockups-0.4.6-py2.6.egg/mockups/base.py", line 236, in process_m2m
    return self.process_field(instance, field)
  File "/usr/lib64/python2.6/site-packages/django_mockups-0.4.6-py2.6.egg/mockups/base.py", line 213, in process_field
    value = self.get_value(field)
  File "/usr/lib64/python2.6/site-packages/django_mockups-0.4.6-py2.6.egg/mockups/base.py", line 210, in get_value
    return generator.get_value()
  File "/usr/lib64/python2.6/site-packages/django_mockups-0.4.6-py2.6.egg/mockups/generators.py", line 64, in get_value
    value = self.generate()
  File "/usr/lib64/python2.6/site-packages/django_mockups-0.4.6-py2.6.egg/mockups/generators.py", line 511, in generate
    self._generator = self.get_generator(self.field, *_self.kwargs)
  File "/usr/lib64/python2.6/site-packages/django_mockups-0.4.6-py2.6.egg/mockups/generators.py", line 571, in get_generator
    max_count=max_count,
  File "/usr/lib64/python2.6/site-packages/django_mockups-0.4.6-py2.6.egg/mockups/generators.py", line 478, in __init__
    self.queryset = queryset.filter(*_limit_choices_to)
TypeError: filter() argument after *_ must be a mapping, not Q

Thanks for you help

**Comment by sorl** [comment]
fixed to support that Q somewhat now
